apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-localstack
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: delivery-localstack
    app.kubernetes.io/instance: delivery-localstack
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: localstack
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: delivery-localstack
      app.kubernetes.io/component: localstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: delivery-localstack
        app.kubernetes.io/instance: delivery-localstack
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: localstack
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
    spec:
      containers:
      - name: delivery-localstack
        image: localstack/localstack:0.14.4
        ports:
          - containerPort: 4566
        env:
        - name: SERVICES
          value: dynamodb,sqs,sns,sts
        - name: START_WEB
          value: "0"
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                # create profile and dynamo table and item
                - "mkdir ~/.aws \
                   && echo \"[profile localstack]\" >> ~/.aws/config \
                   && echo \"region = ap-northeast-1\" >> ~/.aws/config \
                   && echo \"output = json\" >> ~/.aws/config \
                   && echo \"[localstack]\" >> ~/.aws/credentials \
                   && echo \"aws_access_key_id = test-key\" >> ~/.aws/credentials \
                   && echo \"aws_secret_access_key = test-secret\" >> ~/.aws/credentials \
                   && aws dynamodb create-table --table-name Delivery --attribute-definitions AttributeName=DeliveryNo,AttributeType=S --key-schema AttributeName=DeliveryNo,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --profile localstack --endpoint-url=http://localhost:4566 \
                   && aws dynamodb create-table --table-name Sequence --attribute-definitions AttributeName=Name,AttributeType=S --key-schema AttributeName=Name,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --profile localstack --endpoint-url=http://localhost:4566 \
                   && aws dynamodb put-item --table-name=Sequence --item '{\"Name\": {\"S\": \"Delivery\"}, \"SequenceNumber\": {\"N\": \"0\"}}' --profile localstack --endpoint-url=http://localhost:4566"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-localstack
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: delivery-localstack
    app.kubernetes.io/instance: delivery-localstack
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: localstack
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    app.kubernetes.io/instance: delivery-localstack
    app.kubernetes.io/component: localstack
  ports:
  - name: delivery-localstack-port
    port: 4566
