apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-delivery
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-ms-delivery
        env:
        - name: QUARKUS_PROFILE
          value: aws-local-dev
        #- name: JAVA_VERSION
        #  value: "11"
      initContainers:
      - name: wait-delivery-localstack
        image: busybox
        command: ['sh', '-c', "until nslookup delivery-localstack.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for delivery-localstack; sleep 2; done"]
