---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-delivery
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-delivery
        image: public.ecr.aws/nautible/nautible-app-ms-delivery:253c10a2bdd7ea09afbb49275d07412ee0bbb626
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
