---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-delivery
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-delivery
        image: public.ecr.aws/nautible/nautible-app-delivery:a78505647d034b4c651368102c9facea05d4c988
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
