---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-delivery
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-delivery
        image: public.ecr.aws/nautible/nautible-app-ms-delivery:4b7921d6feb05fa325c6eee5c16edcc9c1766a4a
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
