apiVersion: batch/v1
kind: CronJob
metadata:
  name: delivery-cronjob
  namespace: nautible-app-ms
spec:
  schedule: "*/2 * * * *" # 2分おき
  concurrencyPolicy: Forbid # 多重起動禁止
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0 # リトライなし
      ttlSecondsAfterFinished: 30 # 終了後のPodを削除
      template:
        spec:
          containers:
          - name: delivery-cronjob
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - 'date; curl -v
               -X "POST"
               http://nautible-app-ms-delivery:8080/delivery/confirmShipping/'
          restartPolicy: Never